# for shits and giggles
# yaml-language-server: $schema=./utils/schema.json
version: "1.0.0"
applications:
  - name: make
    package: make
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y make
  - name: gcc
    package: gcc
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y gcc
  - name: g++
    package: g++
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y g++
  - name: git
    package: git
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y git
  - name: node
    package: nodejs
    install:
      - distro: Fedora Linux
        command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && nvm install 21
  - name: python
    package: python
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y python3
  - name: pip
    package: python3-pip
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y python3-pip
  - name: cargo
    package: cargo
    install:
      - distro: Fedora Linux
        command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && . ~/.cargo/env
      - distro: macOS
        command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && . ~/.cargo/env
  - name: bat
    package: bat
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y bat
  - name: fzf
    package: fzf
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y fzf
  - name: jq
    package: jq
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y jq
  - name: zsh
    package: zsh
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y zsh
  - name: tmux
    package: tmux
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y tmux
    dependencies:
      - tmux-plugins
  - name: rg
    package: ripgrep
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y ripgrep
  - name: alacritty
    package: alacritty
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++
      - distro: Fedora Linux
        command: cargo install alacritty
  - name: k9s
    package: k9s
    install:
      - distro: Fedora Linux
        command: brew install derailed/k9s/k9s
      - distro: macOS
        command: brew install derailed/k9s/k9s
  - name: btop
    package: btop
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y btop
  - name: docker
    package: docker
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y docker
  - name: kubectl
    package: kubectl
    install:
      - distro: Fedora Linux
        command: cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo [kubernetes] name=Kubernetes baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/ enabled=1 gpgcheck=1 gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key EOF
      - distro: Fedora Linux
        command: sudo dnf install -y kubectl
  - name: nvim
    package: neovim
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y neovim
  - name: eza
    package: eza
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y eza
  - name: neofetch
    package: neofetch
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y neofetch
  - name: brew
    package: brew
    install:
      - distro: Fedora Linux
        command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  - name: atuin
    package: atuin
    install:
      - distro: Fedora Linux
        command: cargo install atuin && echo 'eval "$(atuin init zsh)"' >> ~/.zshrc
fonts:
  - name: Fira Code
    package: firacode
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y firacode
      - distro: macOS
        command: brew install firacode
dependencies:
  - name: tmux-plugins
    package: tmux-plugins
    install:
      - distro: Fedora Linux
        command: sudo dnf install -y tmux-plugins
      - distro: macOS
        command: brew install tmux-plugins
